DROP TABLE IF EXISTS user;
  
CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  usermame VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified_date DATETIME ON UPDATE CURRENT_TIMESTAMP,
  active BOOLEAN 
);